### PR TITLE
FC fix: Genesis hash should canonical too

### LINKED ISSUE #2835: Genesis block hash not `isCanonical`
`0xbcbb53c61f6b8358614a7dcc9b3e00d953342e397c27280933aa9f24c7f13a65` is apparently an acceptable `parentHash` of `blockNumber` 0x1, but not a canonical finalized block for `fcUV3` for the same block. These cannot both be the case.

```
Nov  5 16:00:12.381 2024 REQUEST 
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "engine_newPayloadV3",
  "params": [
    {
      "parentHash": "0xbcbb53c61f6b8358614a7dcc9b3e00d953342e397c27280933aa9f24c7f13a65",
      "feeRecipient": "0xf97e180c050e5ab072211ad2c213eb5aee4df134",
      "stateRoot": "0x9703dbc8ea1bfb13984d31bfa73abdb63e177aee4f9bc40b5a808b0c48cc947b",
      "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "prevRandao": "0xbcbb53c61f6b8358614a7dcc9b3e00d953342e397c27280933aa9f24c7f13a65",
      "blockNumber": "0x1",
      "gasLimit": "0x17dd79d",
      "gasUsed": "0x0",
      "timestamp": "0x672a410c",
      "extraData": "0xd883010e0c846765746888676f312e32332e32856c696e7578",
      "baseFeePerGas": "0x342770c0",
      "blockHash": "0x2119a26f775ce9806d2b13f86a328a1369bb4fd99c4ba98c5cc0020094a0c508",
      "transactions": [],
      "withdrawals": [],
      "blobGasUsed": "0x0",
      "excessBlobGas": "0x0"
    },
    [],
    "0x8b21a0a0256067676ec4b20d4118ed5bde170d78b4e9a8db1f7b7640d3b8b7c0"
  ]
}

Nov  5 16:00:12.383 2024 RESPONSE (status 200 OK) 
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "status": "VALID",
    "latestValidHash": "0x2119a26f775ce9806d2b13f86a328a1369bb4fd99c4ba98c5cc0020094a0c508"
  }
}

Nov  5 16:00:12.489 2024 REQUEST 
{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "engine_forkchoiceUpdatedV3",
  "params": [
    {
      "headBlockHash": "0x2119a26f775ce9806d2b13f86a328a1369bb4fd99c4ba98c5cc0020094a0c508",
      "safeBlockHash": "0xbcbb53c61f6b8358614a7dcc9b3e00d953342e397c27280933aa9f24c7f13a65",
      "finalizedBlockHash": "0xbcbb53c61f6b8358614a7dcc9b3e00d953342e397c27280933aa9f24c7f13a65"
    },
    null
  ]
}

Nov  5 16:00:12.491 2024 RESPONSE (status 200 OK) 
{
  "jsonrpc": "2.0",
  "id": 3,
  "error": {
    "code": -38002,
    "message": "finalized block not canonical"
  }
}
```

See `devops@lodestar-nimbusel-1.mekong-devnet-0.ethpandaops.io` for complete logs.

### PR DESCRIPTION
**Pull request by jangko**
fix #2835

### CODE REVIEW

File: nimbus/core/chain/forked_chain.nim [hunk 1]
```diff
@@ -432,6 +432,7 @@ proc init*(
   except BlockNotFound:
     raiseAssert "Base header missing for #" & $base
 
+  debugEcho "BASE HASH: ", baseHash
```
Comment (tersec) [inline nimbus/core/chain/forked_chain.nim:435]: `debugEcho` probably shouldn't be in production code

Comment (tersec) [reply nimbus/core/chain/forked_chain.nim]: https://github.com/status-im/nimbus-eth1/pull/2839/commits/ad56049731d34638e6c1cc1aa92c215f5aa9d58c
