### PR TITLE
rpc fixes and enable kurtosis

### LINKED ISSUE #2679: `eth.getTransactionReceipt` not registered rpc method
Here for all the cases, `addHttpService` and `addEngineApiServices` is adding the same serverAPI endpoints 
https://github.com/status-im/nimbus-eth1/blob/e19790614b1aba129bfc53bf12202a24956efd08/nimbus/rpc.nim#L267-L302

Thus resulting the eth endpoints being available mentioned in #2677 , but not all of them
For example `eth.getTransactionReceipt()` when called 
```bash
> eth.getTransactionReceipt("")
Error: 'eth_getTransactionReceipt' is not a registered RPC method
	at web3.js:6387:9(39)
	at send (web3.js:5116:62(29))
	at <eval>:1:26(3)
```

### PR DESCRIPTION
**Pull request by advaita-saha**
Once the blocks get's persisted to the db, the rpc can't serve it through the `ForkedChainRef`
Resulting in older blocks returning `null`

Screenshot_2024-10-02_at_3 26 09_PM

Also fixes #2679

### CODE REVIEW

File: nimbus/rpc/server_api.nim [hunk 1]
```diff
@@ -50,7 +50,12 @@ proc headerFromTag(api: ServerAPIRef, blockTag: BlockTag): Result[common.BlockHe
       return err("Unsupported block tag " & tag)
   else:
     let blockNum = common.BlockNumber blockTag.number
-    return api.chain.headerByNumber(blockNum)
+    let blkhdr = api.chain.headerByNumber(blockNum).valueOr:
+      try:
+        api.chain.db.getBlockHeader(blockNum)
```
Comment (jangko) [inline nimbus/rpc/server_api.nim:55]: `getBlockHeader` already in `headerByNumber` https://github.com/status-im/nimbus-eth1/blob/e19790614b1aba129bfc53bf12202a24956efd08/nimbus/core/chain/forked_chain.nim#L601

**Comment by tersec** [comment]
This seems ok as a stop-gap, to get things running. But already needing two separate implementations of this, and probably more over time, each of which has to duplicate the logic, seems suboptimal.

File: nimbus/rpc/server_api.nim [hunk 2]
```diff
@@ -74,7 +79,12 @@ proc blockFromTag(api: ServerAPIRef, blockTag: BlockTag): Result[EthBlock, strin
       return err("Unsupported block tag " & tag)
   else:
     let blockNum = common.BlockNumber blockTag.number
-    return api.chain.blockByNumber(blockNum)
+    let blk = api.chain.blockByNumber(blockNum).valueOr:
+      try:
+        api.chain.db.getEthBlock(blockNum)
```
Comment (jangko) [inline nimbus/rpc/server_api.nim:84]: perhaps move this into `ForkedChainRef.blockByNumber`?

Comment (advaita-saha) [reply nimbus/rpc/server_api.nim:84]: Yeah makes more sense

**Comment by advaita-saha** [comment]
With this PR
All kurtosis tests pass. in a network of nimbus-eth1 and nimbus-eth2
TxPool works only when transactions are very low
All op code tests pass and chain stability tests pass

After the merge of this PR, kurtosis CI will help up not to regress from this point

File: nimbus/rpc/server_api.nim [hunk 3]
```diff
@@ -258,3 +259,40 @@ proc setupServerAPI*(api: ServerAPIRef, server: RpcServer) =
...
+    ##
+    ## data: Hash of a transaction.
+    ## Returns ReceiptObject or nil when no receipt was found.
+    var
+      idx = 0'u64
+      prevGasUsed = GasInt(0)
+    
+    let txHash = data.ethHash()
+    if api.chain.txRecords.hasKey(txHash):
+      let blockhash = api.chain.txRecords[txHash]
```
Comment (jangko) [inline nimbus/rpc/server_api.nim:274]: Probably we can put both block hash and tx index into `txRecords` to optimize this a bit. `rlpHash` is a bit expensive. integer compare is much faster.

File: nimbus/rpc/server_api.nim [hunk 4]
```diff
@@ -258,3 +259,40 @@ proc setupServerAPI*(api: ServerAPIRef, server: RpcServer) =
...
+      let blkdesc = api.chain.memoryBlocks[blockhash]
+      
+      for i, receipt in blkdesc.receipts:
+        let gasUsed = receipt.cumulativeGasUsed - prevGasUsed
+        prevGasUsed = receipt.cumulativeGasUsed
+        if txHash == blkdesc.blockTransactions[i].rlpHash:
```
Comment (jangko) [inline nimbus/rpc/server_api.nim:280]: and then we can compare i with tx index here

File: nimbus/core/chain/forked_chain.nim [hunk 5]
```diff
@@ -570,6 +577,15 @@ func latestHash*(c: ForkedChainRef): Hash256 =
 func baseNumber*(c: ForkedChainRef): BlockNumber =
   c.baseHeader.number
 
+func txRecords*(c: ForkedChainRef): Table[Hash256, Hash256] =
```
Comment (jangko) [inline nimbus/core/chain/forked_chain.nim:580]: hmm, looks like returning a table is expensive. Why not return only what we need? e.g. transactions or receipts?

File: nimbus/core/chain/forked_chain.nim [hunk 6]
```diff
@@ -570,6 +577,15 @@ func latestHash*(c: ForkedChainRef): Hash256 =
...
+  c.txRecords
+
+func memoryBlocks*(c: ForkedChainRef): Table[Hash256, BlockDesc] =
```
Comment (jangko) [inline nimbus/core/chain/forked_chain.nim:583]: ditto

File: nimbus/core/chain/forked_chain.nim [hunk 7]
```diff
@@ -570,6 +577,15 @@ func latestHash*(c: ForkedChainRef): Hash256 =
...
+  c.blocks
+
+func blockTransactions*(b: BlockDesc): seq[Transaction] =
```
Comment (jangko) [inline nimbus/core/chain/forked_chain.nim:586]: ditto

**Review by jangko — APPROVED** [review]
