### PR TITLE
Fix engine_forkchoiceUpdated bug

### LINKED ISSUE #2271: `engine_forkchoiceUpdatedV1`/`V2`/`V3` allow beginning payload build process if `forkchoiceState.headBlockHash` references a `VALID` ancestor of the head of canonical chain
https://github.com/ethereum/execution-apis/blob/v1.0.0-beta.4/src/engine/paris.md#specification-1 notes:
> 2. Client software **MAY** skip an update of the forkchoice state and **MUST NOT** begin a payload build process if `forkchoiceState.headBlockHash` references a `VALID` ancestor of the head of canonical chain, i.e. the ancestor passed [payload validation](#payload-validation) process and deemed `VALID`. In the case of such an event, client software **MUST** return `{payloadStatus: {status: VALID, latestValidHash: forkchoiceState.headBlockHash, validationError: null}, payloadId: null}`.

But
https://github.com/status-im/nimbus-eth1/blob/bda760f41dac22f66c9a3ffa56d25bd2f274f4d1/nimbus/beacon/api_handler/api_forkchoice.nim#L130-L136
combined with
https://github.com/status-im/nimbus-eth1/blob/bda760f41dac22f66c9a3ffa56d25bd2f274f4d1/nimbus/beacon/api_handler/api_forkchoice.nim#L188-L207

allow exactly this.

### LINKED ISSUE #2272: `engine_forkchoiceUpdatedV2`/`V3` inappropriately validate terminal PoW block conditions
https://github.com/ethereum/execution-apis/blob/v1.0.0-beta.4/src/engine/shanghai.md#specification-1
> 1. Client software **MAY NOT** validate terminal PoW block conditions in the following places:
>    - during payload validation (point (2) in the [Payload validation](./paris.md#payload->validation) routine specification),
>    - when updating the forkchoice state (point (3) in the [`engine_forkchoiceUpdatedV1`](./paris.md#engine_forkchoiceupdatedv1) method specification).

but
https://github.com/status-im/nimbus-eth1/blob/bda760f41dac22f66c9a3ffa56d25bd2f274f4d1/nimbus/beacon/api_handler/api_forkchoice.nim#L103-L128
runs regardless of which `forkchoiceUpdated` is called, even though that check should only be run for `engine_forkchoiceUpdatedV1`.

### PR DESCRIPTION
**Pull request by jangko**
fix #2271
fix #2272

### CODE REVIEW

File: nimbus/beacon/api_handler/api_forkchoice.nim [hunk 1]
```diff
@@ -102,38 +102,40 @@ proc forkchoiceUpdated*(ben: BeaconEngineRef,
...
+        ttd = com.ttd.get(high(common.BlockNumber))
+
+      if not db.getTd(blockHash, td) or (blockNumber > 0'u64 and not db.getTd(header.parentHash, ptd)):
+        error "TDs unavailable for TTD check",
+          number = blockNumber,
+          hash = blockHash.short,
+          td = td,
+          parent = header.parentHash.short,
+          ptd = ptd
+        return simpleFCU(PayloadExecutionStatus.invalid, "TDs unavailable for TDD check")
```
Comment (tersec) [inline nimbus/beacon/api_handler/api_forkchoice.nim:119]:
```suggestion
        return simpleFCU(PayloadExecutionStatus.invalid, "TDs unavailable for TTD check")
```

File: nimbus/beacon/api_handler/api_forkchoice.nim [hunk 2]
```diff
@@ -102,38 +102,40 @@ proc forkchoiceUpdated*(ben: BeaconEngineRef,
...
-    if td < ttd or (blockNumber > 0'u64 and ptd > ttd):
-      notice "Refusing beacon update to pre-merge",
-        number = blockNumber,
-        hash = blockHash.short,
-        diff = header.difficulty,
-        ptd = ptd,
-        ttd = ttd
-
-      return invalidFCU("Refusing beacon update to pre-merge")
+  if apiVersion == Version.V1:
```
Comment (tersec) [inline nimbus/beacon/api_handler/api_forkchoice.nim:105]: Would be nice to link https://github.com/ethereum/execution-apis/blob/v1.0.0-beta.4/src/engine/shanghai.md#specification-1 here to explain why this seemingly odd condition (i.e. to clarify it's from spec, not a random implementation issue)

Comment (tersec) [reply nimbus/beacon/api_handler/api_forkchoice.nim:108]: https://github.com/status-im/nimbus-eth1/pull/2274/commits/a90994163555055dcedf27a7c15f9b37fb684d51

File: nimbus/beacon/api_handler/api_forkchoice.nim (hunk 1 above)
Comment (tersec) [reply nimbus/beacon/api_handler/api_forkchoice.nim]: https://github.com/status-im/nimbus-eth1/pull/2274/commits/694f4cd604fa1d8c8b8beced4fa2fe6321c33550

File: nimbus/beacon/api_handler/api_forkchoice.nim [hunk 3]
```diff
@@ -102,38 +102,43 @@ proc forkchoiceUpdated*(ben: BeaconEngineRef,
...
   # probably resyncing. Ignore the update.
   var canonHash: common.Hash256
   if db.getBlockHash(header.blockNumber, canonHash) and canonHash == blockHash:
-    # TODO should this be possible?
-    # If we allow these types of reorgs, we will do lots and lots of reorgs during sync
-    notice "Reorg to previous block", blockHash
+    notice "Ignoring beacon update to old head",
+      blockHash=blockHash.short,
+      blockNumber=header.blockNumber
+    return validFCU(none(PayloadID), blockHash)
```
Comment (tersec) [inline nimbus/beacon/api_handler/api_forkchoice.nim:141]: Maybe worth noting https://github.com/ethereum/execution-apis/blob/v1.0.0-beta.4/src/engine/paris.md#specification-1 specifically here too -- as in, this is likewise not an arbitrary implementation decision. The ignoring beacon update on its own kind of is (and sure, why not), but that it some how has to ensure that it does something like a
```nim
    return validFCU(none(PayloadID), blockHash)
```
rather than risk falling through to the block production codepath is a spec-driven constraint.

The overall point is, when the behavior of the code is dictated by external specs, to document that.

Comment (tersec) [reply nimbus/beacon/api_handler/api_forkchoice.nim:143]: https://github.com/status-im/nimbus-eth1/pull/2274/commits/f68c619e0541aa81be09082e1d47c6b509c33faf

**Review by tersec — APPROVED** [review]
