### PR TITLE
Remove exceptions from EVM

### LINKED ISSUE #2267: Remove exceptions from EVM
Using exceptions in the EVM for violations is prone to extreme slowdowns due to how inefficient exceptions are on the unhappy path - here's a profiling sample from around the 2.3M block height where block processing slows down to a crawl:

image

```
CPU Time
1 of 92: 49.8%  (125.700s of 252.274s)

libgcc_s-14-20240522.so.1 ! _Unwind_Backtrace - unwind.inc
nimbus ! backtrace_simple + 0x35 - simple.c:108
nimbus ! get_program_counters_c + 0xcd - libbacktrace_wrapper.c:296
nimbus ! getProgramCounters__OOZvendorZnim45libbacktraceZlibbacktrace_35 + 0x34 - @m..@svendor@snim-libbacktrace@slibbacktrace.nim.c:159
nimbus ! auxWriteStackTraceWithOverride__systemZstacktraces_64 + 0x1f - @m..@svendor@snimbus-build-system@svendor@sNim@slib@ssystem@sstacktraces.nim.c:134
nimbus ! raiseExceptionEx + 0x33 - @m..@svendor@snimbus-build-system@svendor@sNim@slib@ssystem.nim.c:7879
nimbus ! consumeGas__evmZinterpreterZgas95meter_16 + 0x1c3 - @mevm@sinterpreter@sgas_meter.nim.c:377
nimbus ! selectVM__evmZinterpreter95dispatch_27 + 0x488d - @mevm@sinterpreter_dispatch.nim.c:36694
nimbus ! executeOpcodes__evmZinterpreter95dispatch_824631 + 0x1c2 - @mevm@sinterpreter_dispatch.nim.c:93893
nimbus ! execCallOrCreate__evmZinterpreter95dispatch_824661 + 0xfe - @mevm@sinterpreter_dispatch.nim.c:94106
nimbus ! postExecComputation__evmZstate95transactions_87 - @mevm@sstate_transactions.nim.c:652
nimbus ! execComputation__evmZstate95transactions_99 + 0x35 - @mevm@sstate_transactions.nim.c:665
nimbus ! runComputation__transactionZcall95common_343 + 0x38 - @mtransaction@scall_common.nim.c:1354
nimbus ! txCallEvm__transactionZcall95evm_661 + 0x1f1 - @mtransaction@scall_evm.nim.c:823
nimbus ! processTransactionImpl__coreZexecutorZprocess95transaction_89 + 0x2ea - @mcore@sexecutor@sprocess_transaction.nim.c:1003
...
```

### PR DESCRIPTION
**Pull request by jangko**
Perf improvements: 
- nim-evm: on my machine,  general state test: 1m59s  -> 1m50s.
- evmc: previously evmc is much slower than nim-evm, but now it also around 1m51s when executing GST.
- overall execution flow of EVM is much better, we don't need to worry about wild exceptions anymore.

Downside:
- The EVM error message is a bit obscured especially for precompiles, but that can be improved. The goal is to avoid allocation when handling error.

fix #2267

### CODE REVIEW

File: nimbus/core/chain/persist_blocks.nim [hunk 1]
```diff
@@ -55,13 +55,8 @@ const
...
   let vmState = BaseVMState()
-  try:
-    # TODO clean up exception handling
-    if not vmState.init(header, c.com):
-      return err("Could not initialise VMState")
-  except CatchableError as exc:
-    return err("Error while initializing VMState: " & exc.msg)
-
+  if not vmState.init(header, c.com):
+    return err("Could not initialise VMState")
```
Comment (arnetheduck) [inline nimbus/core/chain/persist_blocks.nim:59]: ideally we can propagate some error information here (and elsewhere)

File: nimbus/evm/computation.nim [hunk 2]
```diff
@@ -332,10 +331,14 @@ proc writeContract*(c: Computation)
...
-  let codeCost = c.gasCosts[Create].c_handler(0.u256, gasParams).gasCost
+  let
+    gasParams = GasParams(kind: Create, cr_memLength: len)
+    res = c.gasCosts[Create].cr_handler(0.u256, gasParams)
+    codeCost = res.gasCost
+
   if codeCost <= c.gasMeter.gasRemaining:
-    c.gasMeter.consumeGas(codeCost, reason = "Write new contract code")
+    doAssert c.gasMeter.consumeGas(codeCost, 
+      reason = "Write new contract code").isOk
```
Comment (arnetheduck) [inline nimbus/evm/computation.nim:341]:
```suggestion
    c.gasMeter.consumeGas(codeCost, 
      reason = "Write new contract code").expect("enough gas since we just checked")
```

this will give a better error message if the assumption fails

File: nimbus/evm/interpreter/op_handlers/oph_envinfo.nim [hunk 3]
```diff
@@ -26,243 +26,225 @@ import
...
-      cpt.opcodeGastCost(Balance, gasCost, reason = "Balance EIP2929")
-      cpt.stack.push:
-        cpt.getBalance(address)
+    ? cpt.opcodeGastCost(Balance, gasCost, reason = "Balance EIP2929")
+    cpt.stack.push cpt.getBalance(address)
 
   # ------------------
 
-  originOp: Vm2OpFn = proc (k: var Vm2Ctx) {.catchRaise.} =
+  originOp: Vm2OpFn = proc (k: var Vm2Ctx): EvmResultVoid {.catchRaise.} =
```
Comment (arnetheduck) [inline nimbus/evm/interpreter/op_handlers/oph_envinfo.nim:67]: I think we can get rid of catchraise here?

File: nimbus/evm/tracer/legacy_tracer.nim [hunk 4]
```diff
@@ -102,26 +102,24 @@ method captureOpStart*(ctx: LegacyTracer, c: Computation,
     if TracerFlags.EnableAccount in ctx.flags:
       case op
       of Call, CallCode, DelegateCall, StaticCall:
-        if c.stack.values.len > 2:
-          ctx.accounts.incl c.stack[^2, EthAddress]
+        if c.stack.len > 2:
+          ctx.accounts.incl c.stack[^2, EthAddress].unsafeValue
```
Comment (arnetheduck) [inline nimbus/evm/tracer/legacy_tracer.nim:106]: `expect` might be better to use here as well

File: nimbus/evm/computation.nim (hunk 2 above)
Comment (jangko) [reply nimbus/evm/computation.nim]: https://github.com/status-im/nimbus-eth1/pull/2314/commits/d654506f05b2b7c62a0ebe4bccc5202b5ab588ff

File: nimbus/core/chain/persist_blocks.nim (hunk 1 above)
Comment (jangko) [reply nimbus/core/chain/persist_blocks.nim:59]: https://github.com/status-im/nimbus-eth1/pull/2314/commits/d654506f05b2b7c62a0ebe4bccc5202b5ab588ff

File: nimbus/evm/interpreter/op_handlers/oph_envinfo.nim (hunk 3 above)
Comment (jangko) [reply nimbus/evm/interpreter/op_handlers/oph_envinfo.nim]: https://github.com/status-im/nimbus-eth1/pull/2314/commits/d654506f05b2b7c62a0ebe4bccc5202b5ab588ff

File: nimbus/evm/tracer/legacy_tracer.nim (hunk 4 above)
Comment (jangko) [reply nimbus/evm/tracer/legacy_tracer.nim]: https://github.com/status-im/nimbus-eth1/pull/2314/commits/80280c10118ca6b150889fc43896f0a31b6a06c9

File: tests/test_stack.nim [hunk 5]
```diff
@@ -34,82 +32,68 @@ proc stackMain*() =
...
-        defined(cpu64) and
-        (NimMajor, NimMinor, NimPatch) >= (1, 0, 4)):
-        testFailPush("yzyzyzyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz".toBytes)
-
     test "push does not allow stack to exceed 1024":
-      var stack = newStack()
+      var stack = EvmStackRef.new()
       for z in 0 ..< 1024:
-        stack.push(z.uint)
+        check stack.push(z.uint).isOk
```
Comment (arnetheduck) [inline tests/test_stack.nim:38]: oof. we really need to come up with something to make Result more pleasant to use in unit tests

**Review by arnetheduck — APPROVED** [review]
