### PR TITLE
Fix outdated txparse tools

### LINKED ISSUE #3317: Build failure on `txparse`
From a docker build, attempting `make -j8 txparse`:

```
#12 7.317 /nimbus-eth1/tools/txparse/txparse.nim(25, 7) Error: type mismatch
#12 7.317 Expression: validate(tx, FkLondon)
#12 7.317   [1] tx: Transaction
#12 7.317   [2] FkLondon: EVMFork
#12 7.317 
#12 7.317 Expected one of (first mismatch at [position]):
#12 7.317 [1] func validate(self: Rlp)
#12 7.317 
#12 7.359 make: *** [Makefile:377: txparse] Error 1
```

Also, it would be nice if you updated the fork to be Prague, on https://github.com/status-im/nimbus-eth1/blob/master/tools/txparse/txparse.nim#L25, while you're at it.

### PR DESCRIPTION
**Pull request by jangko**
fix #3317

### CODE REVIEW

File: tools/txparse/txparse_test.nim [hunk 1]
```diff
@@ -88,6 +88,7 @@ proc main() =
     collectFileNames(testData, filenames)
 
     for input in filenames:
+      let input = input # Workaround compiler lent issue
```
Comment (tersec) [inline tools/txparse/txparse_test.nim:91]: What happens otherwise?

Comment (jangko) [reply tools/txparse/txparse_test.nim:91]: cannot compile.
```
nimbus-eth1/tools/txparse/txparse_test.nim(93, 27) Error: 'input' is of type <lent TestFile> which cannot be captured as it would violate memory safety, declared here: nimbus-eth1/tools/txparse/txparse_test.nim(90, 9); using '-d:nimNoLentIterators' helps in some cases. Consider using a <ref T> which can be captured.
```
